[workspace]
authors = ["alejandrofontan <fontanvillacampa@gmail.com>", "EmilioOlivastri <emilito.olivastri@gmail.com>"]
channels = ["conda-forge"]
name = "BommieToolkit"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
extract_images = "python scripts/vid2imgs.py"
match_images_by_ns = "python scripts/match_images_by_ns.py"
get_rig_config_json= "python scripts/convert_camchain_to_rig_config.py"
colmap2nerf = { cmd = "python ../scripts/colmap2nerf.py", cwd = "monkey_output" }
extract_images_dev = "python scripts/vid2imgs_dev.py"
visualize_colmap = "python scripts/colmap_rerun.py"
transform_splats = "python scripts/transform_splats.py"


[dependencies]
python = "*"
opencv = "*"
tqdm = "*"
pyyaml = "*"
pillow = ">=12.2.0,<13"
rerun-sdk = ">=0.21,<1"
plyfile = "*"

[environments]
kalibr = {features = ["kalibr"], no-default-feature = true}
colmap = {features = ["colmap"], no-default-feature = true}
nerfstudio = {features = ["nerfstudio"], no-default-feature = true}
uwsfm = {features = ["uwsfm"], no-default-feature = true}
sam = {features = ["sam"], no-default-feature = true}
splatpcl = {features = ["splatpcl"], no-default-feature = true}

########################################################################################################################
########################################################################################################################
# kalibr feature
[feature.kalibr]
channels = ["conda-forge", "esrf-bcu", "robostack-staging"]
platforms = ["linux-64", "osx-arm64"]

[feature.kalibr.tasks]
create_catkin_ws = "rm -rf catkin_ws && mkdir -p catkin_ws/src && cd catkin_ws && catkin init"
git-clone = {cmd = "git clone https://github.com/Tobias-Fischer/kalibr.git catkin_ws/src/kalibr", depends-on = ["create_catkin_ws"] }
build = {cmd = "catkin build -j8 --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.20 -DCMAKE_CXX_STANDARD=14", cwd="catkin_ws", depends-on = ["git-clone"] }
kalibr-calibrate-stereo-rig = {cmd = "./scripts/calibrate_stereo_rig.sh"}

[feature.kalibr.tasks.calibrate-stereo-rig-from-videos]
args = [
  { arg = "calibration_dir", default = "calibration_output" },
  { arg = "calibration_resolution", default = "medium", choices = ["lowest", "low", "medium", "high"] },
  { arg = "video_left", default = "videos/cal_left.MP4" },
  { arg = "video_right", default = "videos/cal_right.MP4" },
  { arg = "calibration_skip", default = "5.0" },
  { arg = "calibration_max_frames", default = "0" },
  { arg = "calibration_target", default = "files/april_10x6.yaml" },
  { arg = "calibration_freq", default = "30" },
]
depends-on = [
  { task = "extract-calibration-left", args = [
    { calibration_dir = "{{ calibration_dir }}" },
    { calibration_resolution = "{{ calibration_resolution }}" },
    { video_left = "{{ video_left }}" },
    { calibration_skip = "{{ calibration_skip }}" },
    { calibration_max_frames = "{{ calibration_max_frames }}" },
  ] },
  { task = "extract-calibration-right", args = [
    { calibration_dir = "{{ calibration_dir }}" },
    { calibration_resolution = "{{ calibration_resolution }}" },
    { video_right = "{{ video_right }}" },
    { calibration_skip = "{{ calibration_skip }}" },
    { calibration_max_frames = "{{ calibration_max_frames }}" },
  ] },
]
inputs = [
  "scripts/calibrate_stereo_rig.sh",
  "{{ calibration_target }}",
  "{{ calibration_dir }}/cam0/**/*",
  "{{ calibration_dir }}/cam1/**/*",
]
outputs = [
  "{{ calibration_dir }}/calibration.bag",
  "{{ calibration_dir }}/calibration-camchain.yaml",
  "{{ calibration_dir }}/calibration-results-cam.txt",
  "{{ calibration_dir }}/calibration-report-cam.pdf",
]
cmd = "./scripts/calibrate_stereo_rig.sh images_folder_left={{ calibration_dir }}/cam0 images_folder_right={{ calibration_dir }}/cam1 output_folder={{ calibration_dir }} verbose=0 create_bag=1 target={{ calibration_target }} freq={{ calibration_freq }}"

[feature.kalibr.dependencies]
python = "3.12.*"
ros-noetic-desktop="*"
compilers="*"
cmake="<4"
cctools="*"
pkg-config="*"
make="*"
ninja="*"
colcon-common-extensions="*"
catkin_tools="*"
rosdep="*"
libboost-devel="*"
tapi="*"
suitesparse = "7.*"
tbb-devel="*"
opencv="*"
pip="*"
scipy="*"
matplotlib="*"
ipython="*"
wxpython ="*"
tk ="*"
pyx="*"
libtiff="*"
tqdm="*"
av = "*"
pillow = "*"
ffmpeg-python = "*"
ffmpeg = "*"
exiftool = "*"
eigen = "*"
eigen-abi-devel = "3.4.*"
ros-dev-tools = "*"

[feature.kalibr.pypi-dependencies]
igraph="*"

[feature.kalibr.target.linux-64.dependencies]
libv4l="*"

########################################################################################################################
########################################################################################################################
# sam feature
[feature.sam]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[feature.sam.system-requirements]
cuda = "12.6"

[feature.sam.tasks]
create_masks = {cmd = "python sam3_gradio_app.py", cwd="scripts"}

[feature.sam.pypi-options]
no-build-isolation = true

[feature.sam.pypi-dependencies]
sam3 = { git = "https://github.com/BommieToolkit/sam3_bommie" }

[feature.sam.dependencies]
# Core Python + GPU
python = "3.12.*"
pip = "*"
setuptools="80.*"
pkg-config="*"
torchvision = "*"
numpy = "1.26.*"
scipy = "1.16.*"
pandas = "2.3.*"
opencv = "*"              # image processing
typing_extensions = "*"

# Utilities
ffmpeg = "*"              # video handling
tqdm = "*"
timm = "*"
ftfy = "==6.1.1"
regex = "*"
iopath = "*"
huggingface_hub = ">=0.23"
gradio = "*"
einops = ">=0.8.2,<0.9"
pycocotools = ">=2.0.11,<3"
psutil = ">=7.2.2,<8"

[feature.sam.target.linux-64.dependencies]
pytorch-gpu = "*"

# CUDA
# CUDA Build Tools
cuda-compiler = "*"
cuda-version = "12.6.*"
cuda-cudart-dev = "*"
cuda-crt = "*"
libcusparse-dev = "*"
cuda-driver-dev = "*"
cuda-nvcc = "*"
cuda-nvrtc-dev = "*"
cuda-nvtx = "*"
cuda-nvtx-dev = "*"
cuda-nvml-dev = "*"
cuda-profiler-api = "*"

# CUDA Libraries
cudnn = "*"
libcublas-dev = "*"
libcudss-dev = "*"
libcufile-dev = "*"
libcufft-dev = "*"
libcurand-dev = "*"
libcusolver-dev = "*"
cusparselt = "*"
libnvjitlink = "*"

[feature.sam.target.linux-64.pypi-dependencies]
decord = ">=0.6.0, <0.7"

[feature.sam.target.osx-arm64.dependencies]
pytorch = "*"

########################################################################################################################
########################################################################################################################
# colmap feature
[feature.colmap]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[feature.colmap.system-requirements]
cuda = "12.6"

[feature.colmap.dependencies]
python = "*"
opencv = "*"
tqdm = "*"
pillow = ">=12.2.0,<13"
numpy = "*"
ffmpeg = "*"
pyyaml = "*"

[feature.colmap.target.linux-64.dependencies]
colmap = { build="*cuda*", version = ">=3.12,<3.13" }

[feature.colmap.target.osx-arm64.dependencies]
colmap = { version = ">=3.12,<3.13" }

[feature.colmap.tasks]


########################################################################################################################
########################################################################################################################
# nerfstudio feature
[feature.nerfstudio]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[feature.nerfstudio.dependencies]
git = "*"

[feature.nerfstudio.tasks]

[feature.nerfstudio.tasks.nerfstudio-clone]
outputs = ["nerfstudio/pixi.toml"]
cmd = "test -d nerfstudio || git clone https://github.com/Tobias-Fischer/nerfstudio.git nerfstudio"

[feature.nerfstudio.tasks.nerfstudio-post-install]
depends-on = ["nerfstudio-clone"]
inputs = ["nerfstudio/pixi.toml", "nerfstudio/pyproject.toml"]
outputs = ["nerfstudio/.bommie/post-install.stamp"]
cmd = "mkdir -p nerfstudio/.bommie && touch nerfstudio/.bommie/post-install.stamp"

########################################################################################################################
########################################################################################################################
# uwsfm feature
[feature.uwsfm]
channels = ["https://prefix.dev/conda-forge", "emilioolivastri"]
platforms = ["linux-64"]

[feature.uwsfm.system-requirements]
cuda = "12.4"

[feature.uwsfm.pypi-dependencies]
uwsfm = { git = "https://github.com/EmilioOlivastri/PinaxPython.git" }

[feature.uwsfm.tasks.pinax-clone]
outputs = ["pinax/pixi.toml"]
cmd = "test -d pinax || git clone https://github.com/EmilioOlivastri/PinaxPython.git pinax"

[feature.uwsfm.tasks.pinax-post-install]
depends-on = ["pinax-clone"]
inputs = ["pinax/pixi.toml"]
outputs = ["pinax/.bommie/post-install.stamp"]
cmd = "mkdir -p pinax/.bommie && touch pinax/.bommie/post-install.stamp"


[feature.uwsfm.dependencies]
refractive_colmap = "==3.9.0"
calibmar = "==1.1.0"
git = "*"

[feature.uwsfm.tasks.build-no-display-stub]
outputs = ["scripts/no_display.so"]
cmd = "gcc -shared -fPIC -o scripts/no_display.so scripts/no_display.c"


########################################################################################################################
########################################################################################################################
# splat2pointcloud feature
[feature.splatpcl]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[feature.splatpcl.dependencies]
git = "*"

[feature.splatpcl.tasks]


[feature.splatpcl.tasks.splat2pointcloud-clone]
outputs = ["3dgs2pc/pixi.toml"]
cmd = "test -d 3dgs2pc || git clone -b bommie_toolkit https://github.com/EmilioOlivastri/3DGS-to-PC 3dgs2pc"


[feature.splatpcl.tasks.splat2pointcloud-post-install]
depends-on = ["splat2pointcloud-clone"]
inputs = ["3dgs2pc/pixi.toml"]
outputs = ["3dgs2pc/.bommie/post-install.stamp"]
cmd = "mkdir -p 3dgs2pc/.bommie && touch 3dgs2pc/.bommie/post-install.stamp"


[feature.splatpcl.tasks.convert-splats]
depends-on = ["splat2pointcloud-post-install"]
cmd = "pixi run --manifest-path 3dgs2pc/pixi.toml convert-splats"

[feature.splatpcl.tasks.visualize_colmap_3dgs]
depends-on = ["splat2pointcloud-post-install"]
cmd = "pixi run --manifest-path 3dgs2pc/pixi.toml python scripts/colmap_rerun.py"